Repository Legion2/CorsairLightingProtocol, pull requests merged in 2020-06, with the labels that each got.

#143 added fixIcueBrightness util function
  README.md
  examples/AdditionalFeatures/AdditionalFeatures.ino
  src/FastLEDControllerUtils.cpp
  src/FastLEDControllerUtils.h
Labels: enhancement

#147 fixed scale function when scaling down
  src/FastLEDControllerUtils.cpp
Labels: bug

#152 Update response size from 64 bytes to 16 bytes
  examples/HoodLoader2CLPBridge/CLPUSBSerialBridge.cpp
  examples/HoodLoader2CLPBridge/CLPUSBSerialBridge.h
  src/CorsairLightingProtocolConstants.h
  src/CorsairLightingProtocolHID.cpp
  src/RawHID.h
Labels: bug

#153 Added compatible software badges
  README.md
  extra/images/OpenRGBBadge.png
  extra/images/RGBSyncDarkBadge.png
  extra/images/iCUEDarkBadge.png
Labels: documentation

#154 added support for LT100 Smart Lighting Towers
  .github/workflows/push.yml
  examples/LT100/LT100.ino
  src/CorsairLightingFirmware.cpp
  src/CorsairLightingFirmware.h
  src/CorsairLightingProtocolConstants.h
  src/FastLEDController.cpp
  src/FastLEDController.h
  src/LEDController.cpp
  src/LEDController.h
Labels: enhancement
